name: Publish new module release
env:
  sot: oStack
  module_path: "%%module_path%%"
  module_source: "%%module_source%%"
  run_number: ${{ github.event.inputs.run_number || 1 }}
  max_runs: 3

on:
  push:
    paths:
      - docs/CHANGELOG.md
  workflow_dispatch:
    inputs:
      published_version:
        description: Version to use (if already published)
        required: false
      run_number:
        description: Specify run number (to limit number of retries)
        required: false
jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish Release
    outputs:
      module-version: ${{ steps.version.outputs.module-version }}
      next-version: ${{ steps.version.outputs.next-version }}
    steps:
      - name: Checkout
        if: github.event.inputs.published_version == ''
        uses: actions/checkout@v2

      - name: Setup Node.js
        if: github.event.inputs.published_version == ''
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        if: github.event.inputs.published_version == ''
        run: yarn install --frozen-lockfile

      - name: Publish semantic release
        if: github.event.inputs.published_version == ''
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: yarn semantic-release -e ./.config/release.config.js

      - name: Use specified version
        if: github.event.inputs.published_version
        run: echo ${{ github.event.inputs.published_version }} > VERSION

      - name: Output versions
        id: version
        continue-on-error: true
        run: next_version=$(cat VERSION); echo "::set-output name=next-version::$next_version" && echo "::set-output name=module-version::>= $next_version, < $(expr ${next_version%%.*} + 1).0.0"

  pull-request:
    needs: release
    if: needs.release.outputs.next-version
    runs-on: ubuntu-latest
    name: Create pull request on source repo
    steps:
      - run: echo ${{needs.release.outputs.next-version}}

      - name: Checkout ${{ env.sot }} monorepo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/${{ env.sot }}
          token: ${{ secrets.copybara_token }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Replace the module version
        run: perl -0777pi -e's/(\n+(\s*)source\s*=\s*\"(?:[^\/\"]*\/)*${{ env.module_path }}\/?\")\n?(\s*)([\#\/]+\s*version\s*=\s*\"[^\"]*\"\n?|(\S))(?!(?<=v)ersion\s*=)/$1\n$2# version = "$ENV{module_version}"\n$3$5/g' modules/**/*.tf
        env:
          module_version: ${{needs.release.outputs.module-version}}

      - name: Format files
        run: terraform fmt -recursive modules

      - name: Create pull request (Run ${{ env.run_number }}/${{ env.max_runs }})
        id: pullrequest
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.copybara_token }}
          title: Release ${{ env.module_source }} v${{needs.release.outputs.next-version}}
          commit-message: "Feat: Bump ${{ env.module_source }} to v${{needs.release.outputs.next-version}}"
          body: Coming from https://github.com/${{ github.repository }}
          branch: ${{ env.module_path }}/release
          delete-branch: true
          labels: automerge, release

      - name: Enable pull request automerge
        id: automerge
        if: steps.pullrequest.outputs.pull-request-number
        continue-on-error: true
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          repository: ${{ github.repository_owner }}/${{ env.sot }}
          token: ${{ secrets.copybara_token }}
          pull-request-number: ${{ steps.pullrequest.outputs.pull-request-number }}
          merge-method: squash

      - name: Merge pull request (if automerge failed)
        id: manualmerge
        if: steps.pullrequest.outputs.pull-request-number && steps.automerge.outcome != 'success'
        continue-on-error: true
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.copybara_token }}
          script: |
            await github.pulls.merge({
              merge_method: "squash",
              owner: context.repo.owner,
              pull_number: ${{ steps.pullrequest.outputs.pull-request-number }},
              repo: "${{ env.sot }}",
            })

      - name: Restart the workflow if merging failed
        if: steps.pullrequest.outputs.pull-request-number && steps.automerge.outcome != 'success' && steps.manualmerge.outcome != 'success' && env.run_number < env.max_runs
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.copybara_token }}
          script: |
            const run = await github.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            })

            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: run.data.workflow_id,
              ref: context.ref,
              inputs: {
                run_number: (${{ env.run_number }} + 1).toString(),
                published_version: "${{needs.release.outputs.next-version}}"
              }
            })

      - name: Merging failed ${{ env.max_runs }} times
        if: steps.pullrequest.outputs.pull-request-number && steps.automerge.outcome != 'success' && steps.manualmerge.outcome != 'success' && env.run_number >= env.max_runs
        run: exit 1
